### ISSUE TITLE
Space on the left side of the tab when using ScrollableTab

### ISSUE THREAD

**Issue by mikeemoves** [shyamexe/scrollable_tab_view#17]
Hello. im just new in flutter, how can i  make the tab to the left most of the screen? i upload a image for the reference. also my code

`Headers
final List<String> _tabHeaders = [
    "Pertinent Data",
    "Contact Details",
    "Dependents",
    "Contract Details",
    "Residents",
  ];
`

`Column(
                            children: [
                              ScrollableTabViewWithController(
                                controller: _tabController,
                                children: [
                                  Column(
                                    children: [
                                      ScrollableTab(
                                        labelColor: Colors.black,
                                        indicatorColor: AppColors.bgColor,
                                        isScrollable: true,
                                        onTap: (value) {},
                                        tabs: List.generate(
                                            _tabHeaders.length,
                                            (index) => Tab(
                                                  text: _tabHeaders[index],
                                                )),
                                        children: List.generate(
                                            _tabHeaders.length,
                                            (index) => ListTile(
                                                  title: Column(children: [
                                                    Column(
                                                      children: [
                                                        Text(
                                                          _tabHeaders[index],
                                                          style: TextStyle(
                                                              fontSize: 25,
                                                              fontWeight:
                                                                  FontWeight
                                                                      .bold),
                                                        ),
                                                        SizedBox(height: 15),
                                                        _buildPertinentDataTab()
                                                      ],
                                                    )
                                                  ]),
                                                )),
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          )`

Thank you. 

![image](https://github.com/user-attachments/assets/1e649f9a-1d09-4b03-901e-09b5f8b54a48)

**Comment by shyamexe** [comment]
Hi @mikeemoves 

Thank you for mentioning this missing feature! The `tabBarAlignment` parameter, which allows aligning tabs to the leftmost side with `TabAlignment.start`, will be available in the **next package update**.  

We truly appreciate your feedback and support in helping us identify and address this enhancement. Thanks again for using our package and contributing to its improvement! 😊

Here’s a modified version of your code to ensure the tabs are aligned to the leftmost side:

### Updated Code
```dart
TabBar(
  isScrollable: true,
  tabBarAlignment: TabAlignment.start, // Aligns tabs to the leftmost side
  tabs: [
    Tab(text: 'Pertinent Data'),
    Tab(text: 'Contact Details'),
    Tab(text: 'Dependents'),
    Tab(text: 'Contract Details'),
    Tab(text: 'Residents'),
  ],
)

```
 
If this doesn’t fully achieve your desired effect, feel free to provide more context or adjust the layout further!

**Comment by shyamexe** [comment]
hi @mikeemoves 

The new version of the package, scrollable_tab_view: ^1.0.12, is live now with the tabBarAlignment feature included! I’ll close this issue now as the enhancement has been addressed. Looking forward to the continued improvements! 😊

**Comment by mikeemoves** [comment]
hi @shyamexe thank you so much too 😁
